# Generated by Django 5.2.7 on 2025-12-12 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bookmarked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('social_media', 'Social Media'), ('address', 'Address')], max_length=20)),
                ('label', models.CharField(blank=True, help_text="Optional label like 'Work', 'Home', 'Personal'", max_length=50)),
                ('value', models.TextField(help_text='The contact detail value')),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary contact method')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_methods', to='contacts_app.contact')),
            ],
            options={
                'ordering': ['-is_primary', 'label', 'method_type'],
            },
        ),
    ]
