# Generated by Django 5.2.7 on 2025-12-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
