# Generated by Django 5.2.7 on 2025-12-10 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0002_contact_bookmarked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('social_media', 'Social Media'), ('address', 'Address')], max_length=20)),
                ('label', models.CharField(blank=True, help_text="Optional label like 'Work', 'Home', 'Personal'", max_length=50)),
                ('value', models.TextField(help_text='The contact detail value')),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary contact method')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_methods', to='contacts_app.contact')),
            ],
            options={
                'ordering': ['method_type', '-is_primary', 'label'],
            },
        ),
    ]
