# Generated by Django 5.2.7 on 2025-12-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0003_remove_contact_email_remove_contact_phone_and_more'),
    ]

    operations = [
    ]
