# Generated by Django 5.2.7 on 2025-12-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_app', '0004_migrate_existing_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmethod',
            options={'ordering': ['-is_primary', 'label', 'method_type']},
        ),
    ]
